import com.sun.source.tree.WhileLoopTree;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
public class Student {
    List<String> StudentCourses = new ArrayList<String>();
    public String Name;
    public int rollNumber;
    public String email;

    Scanner sc=new Scanner(System.in);
    static int studen=2112200;

    // 1: ADD STUDENT INFORMATION
    public Student InsertStudent(){

        Student std=new Student();
        String CourseArray[]={"DSA","DMS","COAL","DE","SOCIOLOGY"};
        System.out.println("");
        System.out.println("******************** ADD STUDENT INFORMATION *********************");
        System.out.println("------------------------------------------------------------------");

        System.out.println("Enter Student Name:");
        std.Name= sc.nextLine();
        studen++;

        Scanner emainsc=new Scanner(System.in);

        System.out.println("Enter your Email:");
        std.email= emainsc.nextLine();

        std.rollNumber=studen;
        System.out.println("Student Roll number generated by program: "+std.rollNumber);
        System.out.println("");

        System.out.println("----- Enter Courses you want to Enrolled -----");
        for (int j = 0; j < 5; j++) {
            System.out.println((j)+" "+CourseArray[j]);
        }
        int choice=-1;
        do {
            System.out.println("5: Return to main menu");
            System.out.println("");
            System.out.print("Select Course Number: ");
            choice =sc.nextInt();
            if (choice!=-1 && choice!=5)
            {
                std.StudentCourses.add(CourseArray[choice]);
            }
        }while (choice!=5);
        return std;
    }
}